# congress_fahrplan
# This is the pubspec file specifying all dependencies
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2019 - 2020 Benjamin Schilling

name: congress_fahrplan
description: Congress Fahrplan written in flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  page_view_indicators: ^1.4.0
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  flutter_svg: ^0.19.1
  intl: ^0.16.1
  share: ^0.6.5+4
  device_calendar: ^3.1.0
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
